name: CI pipeline for jest tutorial

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Chechout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: action/setup-node@v4
        with:
          node-version: '20'
          cash: 'npm'
      
      - name: Run test
        run: npm test -- --coverage
